#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="dokku/$APP"
echo "-----> Installing wkhtmltopdf ..."
COMMAND=$(cat <<EOF
apt-get -y  update
apt-get install -y wget xfonts-base xfonts-75dpi libssl-dev openssl xvfb
cd /tmp && wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.jammy_amd64.deb
apt install -f /tmp/wkhtmltox_0.12.6-1.bionic_amd64.deb
echo "-----> wkhtmltopdf installed!"
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
